# Messenger Server Config
# LOCAL DEV (khong can ngrok):
#server.baseUrl=http://localhost:9080
#server.apiPath=
#server.wsPath=
# NGROK (bo comment, comment dong tren):
 server.baseUrl=  https://cassette-ultimatum-swiftly.ngrok-free.dev
 server.apiPath=/api
 server.wsPath=/ws
